version: '3.8'

services:
  ai-frontend:
    container_name: ai-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    environment:
      APIKEY: ${APIKEY}
      BOTID: ${BOTID}
      COMPLETIONSURL: ${COMPLETIONSURL}
      SYSTEMPROMPT: ${SYSTEMPROMPT}
    restart: always
